name = "nonmove-kpi-gh"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "nonmove-kpi-db"
database_id = "d6d9cd41-f2bc-48b4-b515-90678dde1f9e"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "nonmove-kpi-photos"
